import type { Scrap } from '@jupjup/types';

/**
 * 개발용 목업 데이터. 실제 API 연동 전 화면 검증용.
 */
export const MOCK_SCRAPS: Scrap[] = [
  {
    id: '1',
    userId: 'u1',
    category: 'ai_news',
    title: 'OpenAI, GPT-5 공개 — 멀티모달 추론 능력 대폭 향상',
    url: 'https://example.com/1',
    thumbnail: null,
    summary: 'OpenAI가 차세대 대규모 언어 모델 GPT-5를 발표했다. 이미지·음성·코드 추론 성능이 향상되었다.',
    source: 'AI타임스',
    tags: ['LLM', '생성AI'],
    isRead: false,
    isBookmarked: false,
    deadlineAt: null,
    memo: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: '2',
    userId: 'u1',
    category: 'job_post',
    title: '시니어 React Native 개발자',
    url: 'https://example.com/2',
    thumbnail: null,
    summary: '경력 5년 이상 · 서울 강남',
    source: '토스',
    tags: ['React Native', 'TypeScript', 'Expo'],
    isRead: false,
    isBookmarked: true,
    deadlineAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 3).toISOString(),
    memo: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: '3',
    userId: 'u1',
    category: 'finance',
    title: '미국 ETF 절세 전략 — 5월 양도세 신고 전 점검 포인트',
    url: 'https://example.com/3',
    thumbnail: null,
    summary: '해외 주식 양도세 250만원 공제를 활용하는 절세 전략을 정리했다.',
    source: '한국경제',
    tags: ['ETF', '절세'],
    isRead: true,
    isBookmarked: false,
    deadlineAt: null,
    memo: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    id: '4',
    userId: 'u1',
    category: 'job_news',
    title: 'IT 대기업 상반기 신입 공채 일정 정리',
    url: 'https://example.com/4',
    thumbnail: null,
    summary: '네이버·카카오·라인 등 주요 기업 신입 공채 일정과 전형 단계를 정리했다.',
    source: '잡코리아',
    tags: ['신입', 'IT'],
    isRead: false,
    isBookmarked: false,
    deadlineAt: null,
    memo: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
  },
];
